### ISSUE TITLE
Feature request: Number of parts

### ISSUE THREAD

**Issue by blaues0cke** [rgomezjnr/GcodeFilenameFormat#11]
It would be great to have a placeholder that gets replaced by the number of individual objects.

(always checked https://github.com/Ultimaker/Cura/blob/master/resources/i18n/fdmprinter.def.json.pot and I hope its actually "missing" :-))

**Comment by rgomezjnr** [comment]
Hello blaues0cke,

This has been implemented in the development branch [update-job-name](https://github.com/rgomezjnr/GcodeFilenameFormat/tree/update-job-name) as "object_count - number of objects on the build plate". This hasn't been published yet to the Cura Marketplace since it adds a number of features but changes the slicing workflow (removes Save Gcode button), and it hasn't been fully tested. Are you comfortable with manually downloading and loading this version in Cura, or would you like to see this published in the Cura Marketplace?

**Comment by rgomezjnr** [comment]
Hello blaueS0cke did you have a chance to see my response?

> Are you comfortable with manually downloading and loading this version in Cura, or would you like to see this published in the Cura Marketplace?

**Comment by rgomezjnr** [comment]
Hello @blaues0cke

I released a separate version of the plugin [GFF+](https://marketplace.ultimaker.com/app/cura/plugins/rgomezjnr/GcodeFilenameFormatPlus) which does contain the [object_count] format option. If you have any feedback specific to GFF+, please create a separate issue in [GFF+ Issues](https://github.com/rgomezjnr/GcodeFilenameFormatPlus/issues), thanks.

**Comment by blaues0cke** [comment]
Sorry, missed this! Thank you. Will give this a try the next days! :-)

**Comment by blaues0cke** [comment]
Thank you, can confirm that this works like a charme:

![image](https://user-images.githubusercontent.com/5159398/139529183-5424535c-3aa7-495d-a586-a525ca0be34f.png)
